### ISSUE TITLE
Feedback on branch instruction-set-changes

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#113]

**Comment by apt1002** [comment]
if item.name not in self.items.keys(): <-- Drop ".keys()", which is a pessimisation.

**Comment by apt1002** [comment]
'''Load `item` from the stack to its cache variable.''' <-- I think "cache variable" is the wrong terminology, and likely to be confusing. I suggest "C variable". Same for store, obvs.

**Comment by apt1002** [comment]
check_underflow('({})'.format(effect.items['COUNT'].depth)), <-- Off by one.

I guess technically off by effect.items['COUNT'].size, but that's usually going to be one.

**Comment by apt1002** [comment]
```
if (S->STACK_DEPTH > S->STACK_SIZE) {
        S->BAD = S->STACK_DEPTH - S->STACK_SIZE;
        RAISE(SMITE_ERR_STACK_OVERFLOW);
}
```

This should be an assertion, as it is an invariant that all instructions maintain.

**Comment by rrthomas** [comment]
Depth of `COUNT` off-by-one error: arguably, this is a point against the change we agreed to refer to a stack item by its top-most word, not its bottom-most.

Assertion: there's usually a rule: "no error exits in long-running code". I agree that there's a balance to be struck between this (which can result in hard-to-recover problems in code that doesn't actually misbehave) and data integrity loss (which the failure of such an invariant might typically suggest). Here, though, we raise an error, which is probably better, as the controlling process can clean up after itself rather than being core-dumped, while at the same time it gets a strong signal that running any further is very much at its own risk.

We *could* distinguish implementation errors from programming errors, because the caller might decide to take different actions in the different cases, but note that in this case the actual effect is the same: no memory corruption.

**Comment by apt1002** [comment]
Assertion: my point is that if this test fails then we have already failed to detect and report an earlier error. For example, omitting the check from SET_STACK_DEPTH would be a bug, which would be detected by the assertion, and which should be reported as a bug, not a SMite exception.

**Comment by rrthomas** [comment]
Arguably, omitting the check from `SET_STACK_DEPTH` is not a bug; the spec doesn't actually say the error will be detected at that point, only that it will be detected. (Should probably be nailed down.) A bug would be not detecting the error.

In any case, I don't think crashing the process is an option (because we're a library), so that suggests we should have a separate error code or other flag for reporting errors that definitely indicate implementation bugs; although I do wonder how much that is principally of interest to us rather than users.

We agreed previously that it was not necessary to detect invalid `PC` in a `BRANCH` instruction; however, it makes debugging much easier to require the instruction to perform `NEXT` (and hence detect invalid `PC`). I left the check for stack overflow in `SET_STACK_DEPTH` for the same reason (though it's rather less acute there).

However, I am sympathetic to the idea that "early detection" should be the norm, and we could tighten up the spec accordingly.

**Comment by apt1002** [comment]
I think these are all addressed now.
