### ISSUE TITLE
Convert features to APIs

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#151]
Want to be able to offer features without the front-end.

**Comment by apt1002** [comment]
For now, expose in libsmite the code which features call, e.g. `run_trace()` and `run_specialised()`. Consequential changes to `gen-main`.

Now we can bind whichever functions are useful in Python. In particular, we need `smite_ext()` so that object files designed to be run by `mit` (written in C) can also be run by `smite_shell` (written in Python).
