### ISSUE TITLE
Use of LIT_n instructions in pForth

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#176]
Some statistics of instructions.trace (instructions executed to boot up pForth):

```
NEXT:  8505035 (about 50%)
DUP:   688649
SWAP:  633863
LIT_0: 27199
LIT_1: 26828
LIT:   4790140 (about 30%)
```

This implies that at least 95% of variadic instructions are not preceded by a constant that the specializer understands. Is this because the literal values are usually not 0 or 1? Or because SWAP and DUP are not immediately preceded by a literal? Or could pForth be using
LIT_0 and LIT_1 more?

**Comment by apt1002** [comment]
@rrthomas says pForth now uses these instructions for literals when possible.

**Comment by rrthomas** [comment]
Two observations about the above:

1. `NEXT` is so high because many words contain only one instruction. This will be hardest to "fix" in the case of multiple `CALL`s following each other, where we have sequences of `LIT`, `CALL`, `NEXT`.
2. As @apt1002 reports above, pForth has been fixed to use the `LIT_n` instructions, but it only uses them explicitly. An further improvement is to make `LITERAL,` use them, so that non-constant calls to `LITERAL,` have the opportunity to use these instructions. A further improvement would be to manufacture constants with `NOT`, `NEGATE` etc. I'll do the first for now, keeping this issue open until I do it.

**Comment by apt1002** [comment]
That seems to have fixed it. LIT followed by POP, DUP, SWAP, LOAD or STORE is now vanishingly rare, whereas: LIT_1 POP is common; DUP and SWAP are often preceded by LIT_0 or LIT_1; and LOAD and STORE are often preceded by LIT_0 or LIT_2. This is exactly what I'd expect for 32-bit Mit code.

**Comment by apt1002** [comment]
The following prints out the top 12 digraphs in "instructions.trace":
```
counts = {(x, y): 0 for x in range(32) for y in range(32)}
with open('instructions.trace') as f:
    trace = [int(l) for l in f.readlines()]
    for x, y in zip(trace, trace[1:]): counts[(x, y)] += 1

print(sorted([(count, (x, y)) for (x, y), count in counts.items()], reverse=True)[:12])
```
Currently, they are:
 - LIT NEXT (9.7%)
 - NEXT LIT (8.9%)
 - LIT_2 LOAD (5.6%)
 - NEXT LIT_2 (5.1%)
 - NEXT NEXT (4.9%) <-- !
 - LIT_0 DUP (4.7%)
 - LIT_2 STORE (4.6%)
 - NEXT LIT_0 (4.2%)
 - LOAD NEXT (4.0%)
 - STORE NEXT (3.6%)
 - LIT CALL (3.1%)
 - CALL LIT (3.1%)

These add up to over 60%. There are no control-flow instructions in the top ten digraphs, and no arithmetic instructions in the top twelve. Cutting down the number of NEXTs is probably the next priority.

In interpreting the above digraph frequencies, it may be useful to know the frequencies of instructions. For example, almost all uses of LIT are in these twelve digraphs.
 - NEXT 31.3%
 - LIT 13.1%
 - LIT_2 12.4%
 - LIT_0 7.4%
 - LOAD 6.7%
 - STORE 5.9%
 - DUP 5.1%
 - SWAP 4.7%
 - BRANCH 3.2%
 - CALL 3.1%

**Comment by rrthomas** [comment]
Please could we have this as a utility script? I suggest putting it under a new top-level directory, `util`.

**Comment by rrthomas** [comment]
We have written the script, and will open a new issue to integrate & use it.
