### ISSUE TITLE
More top-of-stack optimisations

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/smite#299]
`gen-specializer` tracks the top of stack. The `more-tos-optimizations` branch allows the `LIT_n` instructions to be implemented in a less special-cased way, by specifying their outputs. This could be generalised:

- Allow expressions as well as constants (handily, most of the basic operations have the same syntax in Python and C), so we can track the effect of monadic operators such as `NEGATE` and `NOT`.
- Add the TOS to the profile, so it is possible to guess it.
- This should make it possible to guess arbitrary values, remove the `LIT_n` instructions, and no longer need to treat the stack operators specially.
- As with the instructions, we will need to "seed" the profile with literal values that we want to guess. These could be the values of the current `LIT_n` instructions, plus the word size.

Questions:

- What do we do if a TOS guess is wrong? Do we "shrink" to a guess with unknown TOS?
- Do we guesses several different TOSes for a State, several different instructions (sequences) for a given TOS, or do we simply have more states?

**Comment by apt1002** [comment]
The only reason we want to know TOS is for the dataflow through variadic instructions. We still need the specialized variadic instructions `FOO_WITH_n`. E.g. executing `SWAP` even immediately after `LIT_2` causes the stack cache to be dumped to memory and reloaded.

All we need do is replace instructions everywhere with specialized instructions, where a specialized instruction is an instruction and a TOS value. This obviates many other ideas, including `LIT_n`.

simulate-jit generates states for the specialized instructions `FOO_WITH_n` instead of `FOO`.

A single guess consists of a specialized instruction: instruction + TOS value.

Multi-guesses:

- [x] Change the pickled labels so that:
  - [x] There is a tuple of pre-guesses: opcodes that must have been guessed correctly to branch to this label. We've written `CompiledLabel.preguess()` but it is not yet exported.
  - [x] The guess field becomes a single specialized instruction. So a multi-guess becomes guessing the single specialized instruction and the pre-guesses of the following label.
- [x] In simulate-jit, states which predict only one path include the opcodes for that path in their pre-guess, and we remove the existing multi-guess code.
- [x] Add an optimization to gen-specializer such that if the multi-guess is a prefix of the pre-guesses, the guess condition can assume that the opcode is correct.

**Comment by apt1002** [comment]
We actually did something a little more general: a guess is an opcode and an arbitrary (side-effect-free) guard condition.

We have not yet converted everything to use SpecializedInstructions.
