### ISSUE TITLE
Delete RAISE_NON_ZERO

### ISSUE THREAD

**Issue by apt1002** [rrthomas/smite#72]
Let's try to keep the error handling in action routines as simple as possible, i.e. "just call RAISE()". This was spoilt in 59b12b51. I can see why, but it was unfortunate.

To restore the simple design, change the specification so that the result code of `smite_single_step()` for "HALT" is non-zero, and the return code for success is zero. Rename `RAISE_NON_ZERO()` back to `RAISE()` and use it everywhere, including in "HALT".

**Comment by rrthomas** [comment]
As in the setting of `STACK_DEPTH`, I think the action code is primary here. The code for `HALT` is zero, so I want to see `RAISE(0)`.

So, the error code for `HALT` could be changed. But `run` should return 0 for a normal halt, and I think it's reasonable for it to be `single_step` that is different; it makes sense to me too that "returning after one step" is more "errory" than "normal `HALT`". (I considered the alternative that `run` has no 'normal' exit, and therefore only returns non-zero codes, allowing `single_step` to return 0 for completion of a single step; but "halting" is a fairly standard thing for a Turing machine to do.)

Finally, I think it's also good that other functions stick to the convention that 0 means success, given that they want to return more than one non-zero error code (otherwise I could use booleans, and 0=failure). The obvious difference is that the fact that the function halted is implicit in getting a return code; there's no separate "HALT" state.

**Comment by rrthomas** [comment]
`RAISE_NON_ZERO` could be renamed `RAISE_IF_ERROR`.

**Comment by apt1002** [comment]
I think it could be argued that non-termination is normal for `run()`, and that HALT is more like an exception, and therefore deserving of a non-zero return code.

If you insist on using zero for HALT, let's make a HALT macro, so that everywhere else can say RAISE.

**Comment by rrthomas** [comment]
I have made the same argument to myself, and found it unconvincing. In the abstract, terminating is a normal thing for programs to do. In the concrete, calling `run` has the feel of `spawn`, not `exec`. This is an interesting case where the principle of least surprise appears to be in conflict with itself!

I have another suggestion. Standard C style is to check error codes (even if this is widely ignored, and hence not the way newer languages tend to work). So let's make `RAISE` always raise an error, and instead check the return codes of functions we wrap. In other words, the real problem here is trying to write in a non-C style. (I do think it's confusing that the `RAISE` macro might do nothing; its name doesn't to me have the flavour of `assert`.)
